apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gowebapp
  namespace: default
spec:
  dnsNames:
{{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
{{- end }}
  secretName: gowebapp-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer